apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform-sealed-secrets-namespace.yaml
  - platform-sealed-secrets.yaml
  - platform-metrics-server.yaml
  - platform-longhorn-namespace.yaml
  - platform-longhorn.yaml
  - secret-smoke-namespace.yaml
  - secret-smoke.yaml
  - storage-smoke-namespace.yaml
  - storage-smoke.yaml
