---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-smoke
  namespace: secret-smoke
spec:
  encryptedData:
    message: AgAVthhY0jyVMLTBkSH713QLRjJ4riErQ5hJpbWB7xlCXwPCPiwxgf0W9qvGA+w0kREG/XVpoyV7SgBB778E4Mym7TZV758E8Itg3FO+IppCivB/4t9uHf/aYYbR4jNSpt1KUeZMRdhHtItQxV+wGj1M50jEjbzr4fPB61lZRniRTX0S/Gqg4ftDb/GasiVSW2t6GQUTxan/0NV02OevAx1XK2UtsrDSys+YTJ7XDBhFq0bceCz+e3JkrMZsy/TJGTX7UCvV2mi2eG7NWSqgDFD1RBi30zGcHc7X7t3f0w7w7zwmMQgfz2YJbsHiCNyOQAR99EQ6THDunruQYKlGoqL4eGY3dUvuPKxAyGsdRalKQdyrmuTnIBC4BEHL4CmO1S7BI0HRoCNxHX1Ig8eFH5b8kLYkxWsz7ckCI3WsIoJVomUd/YSyN5w7aup6har0I6EmNjCvNqWku9x65pmnWuGsvyCiJDDkzK6917oBubxBWoFY3TTZ7BtlqW5Rj18c+qZOpbdPcEIWetYvfj3QBkMa5ONuInUQRFGVkpd79W5VUOLIEh0qzYLTS+0Mu3a7dADemLkL0klIwbpFiwExzwvvCfBcR75YODF39Yo7G3Gx0ymY4O4U5OsYIXRSE/s2d7Tj8jKVBog6/vhkbo2dax/0tXMUrANDcaJ+RKmHSp/8cfqps+v12PDhh8dkBR+BrYH7r+knAmOwDzHBUJQAZalXY+JAuZaUttcv
  template:
    metadata:
      name: secret-smoke
      namespace: secret-smoke
