---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-smoke
  namespace: secret-smoke
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    message: AgCmIDKnk32z5LkQxXuLLxJXp+xYQ+kkBQrJbntJTlEGXnt9Y9NzTDuYhSbtxnl6LEBZUA8XWasqu5ceVikKDTcTJXbUoYMF8cdVo1m2AG3Kl8oVTRRc4h2HVfnbuh3EhfOPUDOMe8M/knq/q0u4HWy9YDbVZ069sgeysFutX0dEbSIwhG4hEUbHf0PKuG5Mfagfc4vGdELKnIp35aJC+3kUpUd5XfDxWQlJqSGGu9XxZedpHPJ4hQ/m7dD9b40STFa94waX7Rtlvo3s95JabfeRDJsfTqxzxVWlh3gO4Z5sTVY/zi5hBC5lhx88cdZhaC9EhanBl2XBOGFwzwZCndi8RQfiieuZQCDjBA/gbTueDLqioJSwZKBdFZLgHaK+d6fDuaBVeJKRVFOxCrDq3VlVKaGnRCIb48ZJDSMqveLoS17noTWrtrz++rq3otQGOgaRr0fJa3skK5mzGSevQtt0iSFCAc07Dp2UGzCuywL7tL7KdY/9vGUokMy4ZtoUfA5xoabI3J8CCMwBKoEtm96WybJm4ziDOa9FqZcRaV3RVO/GaNfYW/NlOR5Di0NgSYwvo6GjlkVKEuzYbiCCIfAJEboLUjiDjTwf+0W8p3h2GJT2mNgTIb6alIgAt8X/xjtR5PodFoY5WYIH/kdR0hWCm1QlhOA3mNueV+/EbGcThH2PXKJr9xXNN8Cp6PUsvk5Gg3ZWmBqEx8RorbYH328W5QPZQpxRoq27
  template:
    metadata:
      name: secret-smoke
      namespace: secret-smoke
